---
name: Quick Test

on:
  push:
    branches:
      - main

jobs:
  quick-test:
    runs-on: ubuntu-latest
    env:
      BUILD_CMD: ${{ secrets.BUILD_CMD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Envs
        run: printenv

      - name: Echo Env
        run: echo "$BUILD_CMD"
